version: '3.8'

services:
  webdav-discord-bot:
    build:
      context: https://github.com/Aureliolo/openolat-webdav-to-discord-bot.git
      dockerfile: Dockerfile
    volumes:
      - /var/lib/openolat:/usr/src/app/database
    environment:
      WEBDAV_URL: your_webdav_url
      COURSEFOLDERS_PATH: your_root_folder_to_watch
      WEBDAV_LOGIN: your_username
      WEBDAV_PASSWORD: your_password
      DISCORD_WEBHOOK: your_discord_bot_webhook
    restart: unless-stopped
